add data
romartiny/innowise-test-tasks pull request #1
Opened 2022-05-29 23:37 UTC by romartiny

2022-05-31 08:33 UTC, nashalda commented on Controller/UserController.php
> +        header("Location: index.php");
всегда после такого редиректа ставь 
exit(); 

пробегись по всему коду

2022-05-31 08:36 UTC, nashalda commented on View/Add.php
> +                        <a class="btn btn-secondary back-button" href="Index.php">Back</a>
Не работает кнопка Back

2022-05-31 08:39 UTC, nashalda commented on users.sql
> +) ENGINE=InnoDB DEFAULT CHARSET=utf8;
Используй кодировку utf8mb4. Почитай про это

2022-05-31 08:45 UTC, nashalda commented on View/Index.php
> +<link href="assets/js/main.js">
стили подключаем через link
скрипты кодключаем через  script

2022-05-31 08:51 UTC, nashalda commented on View/Add.php
> +                <form action="?action=add" method="post">
для action всегда используют лишь имя скрипта, который будет прнимать это форму.
Такой вариант как action="?action=add" в приниципе тоже будет работать, но лучше по классике action="xxx.php" )

Хотя если у тебя есть ссылка, где советуют именно так применять, то я почитаю.

2022-05-31 08:54 UTC, nashalda commented on View/Add.php
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorig
![image](https://user-images.githubusercontent.com/15914080/171133780-46370a2b-bfda-466a-85f7-9a5504eabb57.png)
Очень длинная строка. В шторме есть специальная вертикальная линия, которую рекомендуется не пересекать. А вообще строки должны рекомендуется делать длиной до 120 символов для читаемости кода

2022-05-31 09:04 UTC, nashalda commented on View/Add.php
> +                <h2 class="text-center">UserMove</h2>
Чуть не по PHP - по правилам SEO на странице обязательно должен быть один H1, а уже все остальные H2-H6 - опционально

2022-05-31 09:08 UTC, nashalda commented on View/Index.php
> +<!doctype html>
перечитай PSR-1
Суть в том, что когда мы видим PHP файл с заглавной буквы, то мы знаем, что внутри будет класс.

2022-05-31 09:22 UTC, nashalda commented on View/Index.php
> +            <?php foreach ($this->model->getData() as $key) :?>
https://www.duplicatetransaction.com/wp-content/uploads/2020/06/model-view-controller-mvc-pattern.png
Да, у тебя всё работает, но ты нарушаешь концепцию - модель не взаимодействует с View напрямую - только через контроллер.

2022-05-31 09:23 UTC, nashalda commented on Controller/UserController.php
> +        if($user->id > 0) {
не забывай отбивать код пробелами
в шторме есть сочетание Ctrl + Alt + L - используй его тоже

2022-05-31 09:32 UTC, nashalda commented on Controller/UserController.php
> +        include_once __DIR__ . '/../View/Index.php';
давай использовать require_once вместо include_once.
Почитай на эту тему, потом поговорим

2022-05-31 09:38 UTC, nashalda commented on Model/UserModel.php
> +class UserModel extends Config {
модель не может extends Config

2022-05-31 09:46 UTC, nashalda commented on View/Index.php
> +                    <th class="text-center">Edit Data</th>
Не работает - должно предзаполняться данными, полученными из БД

2022-05-31 09:48 UTC, nashalda commented on View/Index.php
> +                    <th class="text-center">Delete Data</th>
Тут уже про юзабилити - обычно колонкам с действиями не дают имена, потому что на кнопках итак написано что  будет происходить - убери Delete Data и Edit Data

2022-05-31 09:53 UTC, nashalda commented on View/Add.php
> +                            <option>Male</option>
Для option обязательно используй value

2022-05-31 09:58 UTC, nashalda commented on View/Add.php
> +                            <option>Female</option>
<option value="short">Very-very-very-very-very-very-very-very-very-very long string</option>
Это для понимания почему нужно использовать option value. В базу данных мы всегда пишем option value.

2022-05-31 10:00 UTC, nashalda commented on View/Add.php
> +                        <a class="btn btn-secondary back-button" href="Index.php">Back</a>
Сделай небольшой margin-top, чтобы кнопки не прилипали к форме

2022-05-31 14:52 UTC, nashalda commented on users.sql
> +--
Покопайся в настройках. Более корректный дамп будет типа
CREATE DATABASE IF NOT EXISTS `usermove` 
USE `usermove`;

CREATE TABLE IF NOT EXISTS `users` (
  `id` int NOT NULL,
  `name` text NOT NULL,
  `email` text NOT NULL,
  `gender` text NOT NULL,
  `status` text NOT NULL,
  PRIMARY KEY (`id`)

2022-05-31 14:54 UTC, nashalda commented on Controller/UserController.php
> +class UserController extends UserModel
У тебя здесь не будет extends - в них здесь просто нет надобности

2022-05-31 14:55 UTC, nashalda commented on Controller/UserController.php
> +            [$controller, $action]();
Давай всё таки явно вызывать методы - по имени

2022-05-31 15:01 UTC, nashalda commented on View/Index.php
> +                    <th class="text-center">Status</th>
Не хватает ячейки. даже если она пустая она должна быть

2022-05-31 15:01 UTC, nashalda commented on View/Index.php
> +    <a href="?action=newUser" class="btn btn-success">New user</a>
указывай явно скрипт-обработчик в href

2022-05-31 15:03 UTC, nashalda commented on View/Add.php
> +                        <select name="gender" class="form-select col-1">
<label for="gender"
по-моему привязывается к id. Проверь, пожалуйста. 
Если так, то добавь select-у id

2022-05-31 15:06 UTC, nashalda commented on Controller/UserController.php
> +    public function add()
Нигде нет return type declaration and type hinting.
надо добавить к методам

2022-05-31 15:13 UTC, nashalda commented on View/Index.php
> +            <?php foreach ((array)$this->getUserData() as $key) :?>
Сюда уже должен прийти массив.
контроллер - логика
модель - преобразования и работа с данными
вью - вывод подготовленных данных

2022-06-02 12:48 UTC, nashalda commented on View/Add.php
> +    <link rel="stylesheet" href="assets/style.css">
папка assets располагается либо в корне проекта, либо в папке Public/assets

2022-06-02 12:52 UTC, nashalda commented on View/Index.php
> +<!doctype html>
Не сделано.

2022-06-02 13:11 UTC, nashalda commented on Controller/UserController.php
> +        $user->id = $_POST['id'];
По action-ам
Когда мы нажимаем кнопку Add в адресной строке должно появится http://127.0.0.1:3449/index.php?action=add
Когда мы нажимаем кнопку Delete в адресной строке должно появится http://127.0.0.1:3449/index.php?action=delete&edit=22
Когда мы нажимаем кнопку Edit в адресной строке должно появится http://127.0.0.1:3449/index.php?action=edit&id=22
Когда нажимаем кнопку Save, методом ПОСТ должен передаваться параметр save и через hidden поле id=22

2022-06-02 13:37 UTC, nashalda requested changes

2022-06-02 13:37 UTC, nashalda commented on Controller/UserController.php
> +use JetBrains\PhpStorm\NoReturn;
убери. Это работает только в 8 версии пхп. 
Сейчас, если не указано иного, то ориентируемся на версию 7.4

2022-06-02 13:37 UTC, nashalda commented on Controller/UserController.php
> +        $controller = new UserController();
нет никакой нужды здесь созадавать экземпляр класс
$this вполне решает эту проблему

2022-06-02 13:37 UTC, nashalda commented on Controller/UserController.php
> +        $user = new UserModel();
в конструкторе у тебя уже создан экземпляр класса

2022-06-02 13:37 UTC, nashalda commented on Controller/UserController.php
> +    #[NoReturn] public function add(): void
у тебя нет метода edit. нужно создать его

2022-06-02 19:12 UTC, romartiny commented on View/Add.php
> +                <form action="?action=add" method="post">
нужно писать именно - ?action=edit/add

2022-06-03 09:41 UTC, romartiny commented on Controller/UserController.php
> +        $this->model->id = $_POST['id'];
$_POST, $_GET это же controller(logic). Как он может быть в модели?

2022-06-03 16:42 UTC, closed without merging